# Add markdown with redcarpet
markdown: redcarpet
redcarpet:
  extensions: [:fenced_code, :gh_blockcode, :no_intraemphasis]

# Use pygments for syntax highlighting
pygments: true

# When served up, the content is under this path
# baseurl: "/ggplot2"

# When served locally with jekyll, automatically update when files change
auto: true

# Google Analytics
google_analytics_id: UA-67989-15