auto: true

# Add markdown with redcarpet
markdown: redcarpet
redcarpet:
  extensions: [:smart, :fenced_code, :gh_blockcode, :no_intraemphasis]

# Use pygments for syntax highlighting
pygments: true

# When served up, the content is under this path
baseurl: "/ggplot2"